### ISSUE TITLE
Command-line tools

### ISSUE THREAD

**Issue by bastianeicher** [0install/0install.de-feeds#3]
- Sysinternals
- [GnuWin](http://sourceforge.net/projects/gnuwin32/files/)
- [MSYS](http://sourceforge.net/projects/mingw/files/MSYS/)
- MinGW + [http://code.google.com/p/mintty/](mintty)
- [PNG optimizers](http://optipng.sourceforge.net/pngtech/optipng.html)
- cloc.exe
- finddupe.exe, DupeMerge.exe
- zip.exe, zipcloak.exe, zipnote.exe, zipsplit.exe, unzip.exe, unzipsfx.exe, funzip.exe
- bzip2.exe, bunzip2.exe
- bsdtar.exe, bsdcpio.exe
- pathman.exe, setx.exe
- nircmd.exe, nircmdc.exe
- upx.exe
- msxsl.exe, wsremote.exe, filever.exe, linkspeed.exe, now.exe, pmon.exe, sleep.exe, subinacl.exe

**Comment by pmiess** [comment]
In the celebration of the birth of my savior, I offer you a Christmas present. The gnuwin32 packages I've created at [gitlab.pmiess/0install-feeds](https://gitlab.com/pmiess/0install-feeds/tree/master/public/gnuwin32)

All of the latest versions of the packages with tools are there, the doc only packages are not included.
A number of the executable and scripts suffer from hard-coded paths.
I have tried to include all the dependencies using only gnuwin32 tools so that it is self supporting, but a few additional packages are required and not in gnuwin32. 
https://pmiess.gitlab.io/0install-feeds/expat.xml
https://pmiess.gitlab.io/0install-feeds/glut.xml
https://pmiess.gitlab.io/0install-feeds/imagemagick.xml
https://pmiess.gitlab.io/0install-feeds/mingwrep/readline.xml
https://pmiess.gitlab.io/0install-feeds/netcdf.xml
https://pmiess.gitlab.io/0install-feeds/perl/Perl4-CoreLibs.xml
https://pmiess.gitlab.io/0install-feeds/pthreads-win32.xml
https://pmiess.gitlab.io/0install-feeds/unxutils.xml

mingw, binutils, ghostscript, and latex are used and not packaged in several feeds.

All the shell scripts are set up to use bash, the bash packaged in the default feed does not work with them so all of the scripts will fail. Except gettext envsubst 
All the perl scripts are setup to use the default perl feed but the feed does not exist yet and windows native perl installs are not recognized.
I tried using coreutils env to look up perl and bash from the path but env returns before the command is finished and so the output shows up after the next prompt which looks weird. 
Most of the packages include a second archive on github so that  the feeds work when sourceforge is down. 
Most packages use the other packages rather than the deps archives for dependencies, in a few cases this didnt work or I tried them to work around a dependency problem, I it helped once.  The packages with dedicated dependencies have have a version modifier of -2. The packages that forgo the deps archives in favor of other packages have a version modifier of -3.
All the feeds with translations have the languages listed and the translation dir set so other languages could work if the console was set up properly for them.
versions are sometimes the main exe version and sometimes truncated to the published package version. The extended versions should be truncated.
The feeds include zip, bzip2 and bsdtar, bsdcpio in libarchive but a more up to date package might be better


Please let me know how you would like to move these packages here.

**Comment by pmiess** [comment]
Here are some of the problems for the gnuwin32 feeds
* a2ps 
	* a2ps
		* can use ghostview ps2pdf acroread gzip compress bzip2 psutils/psnup, psutils/fixps, groff/grog, texinfo/texi2dvi, mail, book, lp, lpr, display, pdf, file
		* if we keep the config file it needs ./a2ps-site.cfg
		* crashes on execution with imagefile
	* card 
		* has a typo for using a default for env variable A2PS
		* hard codes /bin/rm path
		* segfaults when called
	* fixps hardcodes /bin/rm path
	* tr.exe write error invalid argument
	* oginkify 
		* hardcodes the library path 
		* "c:/progra~1/A2Ps/share/ogonkify/latin2.enc"
	* psdiff command needs binutils/wdiff command
	* psmandup 
		* hardcodes /bin/rm path 
		* tr.exe: write error: invalid argument
	* psset hardcodes /bin/rm path 
	* texi2dvi4ps needs pdflatex, pdftex, makeindex, latex, bibtext texinfo( makeinfo, texindex ) and texlive or miketex 

* autoconf 
	* depends on mingw32 and bin-utils not provided
	* autoheader  error "syntax of the command is incorrect"
	* autom4te fails looking up m4.
	* autoreconf cant find automake

* btyacc fatal - cannot open "/tmp/yacc_a_*" failure

* bzip2 
	* bzcmp/bzdiff /bin/rm hardcoded @ line 59
	* diff fails when reading from piped stdin

* compface crashes

* crafty wants to write to the book files in the current directory and cant
accept dos command line paths to change that. 

* cygutil unix2dos u2d will not work on piped input

* enscript
	* bin/over has hardcoded libarary dir path
	* defaults point to invalid path for lookup states and share

* gcal 
	* all the bash scripts except gcal-moon depend on hard coded install path
and mail not provided
	* gcalltx depends on latex not provided
	* ddiffdrv calls /bin/sh
	* gcal-dst calls zdump from timezone-data not provided

* gdbm conv2gdbm dbminit missing from gdbm3.dll 

* giflib gifburst fails if the gif file name is given including extension

* gri help lists path c:/progra~1/GRI... for Examples and Manual

* groff
	* afmtodit hardcodes groff fontdir to c:/progra~1
	* chem probably hardcodes groff to c:/progra~1
	* groffer 
		* hardcodes binder and libdir to c:/proga~1
		* needs ps2pdf and gs from ghostscript
	* neqn prepends hardcoded path 
	* nroff 
		* could use locale from glibc 
		* prepends hardcoded path 
	* pdfroff needs ghostscript
	* roff2dvi needs ghostscript for ps2pdf and gs

* gzip
	* scripts generated by gzexe do not work it looks like the exe is uncompressed correctly
	* zdiff diff with stdin Invalid argument with piped input
	* zforce doesnt recognized compressed files
	* zcmp cant find /bin/sh

* jpeg
	* jpegexiforient runs but doesnt change exif orientation tag
	* jpegtran leaves artifact column on image rotated 90

* less 
	* lesspipe tempfile command missing and not packaged
	* lessfile tempfile command missing and not packaged
	* -R doesnt display color text

* libtool 
	* libtool 
		* hard coded /usr/bin/sed and /bin/sh and /usr/bin/grep
		* needs ld, nm, gcc, strip, dlltool, objdump, as, ar not packaged
		* library search bath hardcoded to g:/ or 
	* libtoolize  prefix hardcoded to c:/progra~1/LibTool

* netpbm 
	* hpcdtoppm is only a message to go get it elsewhere
	* pcdovtoppm depends on hpcdtoppm and tempfile
	* pnmindex depends on tempfile if title set
	* manweb 
		* expects to be able to fall back to man
		* manweb.conf cant take paths with drive letters 
		* manweb.conf requires absolute paths
	* pamtodjvurle always oom's
	* pamtouil crashes 
	* ppmshadow compilation error
	* eyuvtoppm premature end of file


* palm-imgvtopgm imgvinfo, imgvtopnm, pgmtoimgv require netpbm-9
* palm-imgvtopgm imgvview hardcoded to call xv alias image viewer to xv
* palm-ppmtoTbmp requires netpbm-9 whose package has been deleted

* pgmadd pgmclouds crashes

* psutils
	* fixmacps defaults to c:/progra~1 needs -dir <installdir> to work
	* fixpsditps Unescaped left brace in regex is illegal here in regex
	*
* sgitools iopen: can't open output file on several tools

* sharutils
	* remsync hardcodes tar and diff paths
	* shar attempts to fork function not implemented

* sunrpcgen needs cpp

* t1lib fails to load font.

* tar cant fork for (un)compressing output

* Texinfo 
	* texi2dvi 
		* requires tex for tex, bibtext, thumbpdf, makeinfo 
		* requires hevea to convert to html
		* icon types wrong
	* infokey crashes if envrionmental variable home doesnt exist

* ttf2pt1
	* ttf2pt1_convert hardcoded dirs to c:/progra~1/...
	* ttf2ps1_x2gs requires ghostscript
	* dmpf fatal error

* unzip uzexampl invalid dll version

* urt
	* applymap crashes
	* rletoascii says unrecognized opcode -8 or -12 on some output files
	* rletoalias crashes
	* rletogif only handles single channel images ?

* util-linux-ng whereis doesn't find anything.

* wget only works on tls1 or http

* wv
	* wvPS requires latex and dvips from tex
	* wvPDF requires Adobe distiller or ps2pdf from ghostscript
	* wvMime requires wvPS, wvLatex and gv ggv or ghostview
	* wvDVI requires latex
	* wvText optionally uses elinks, links, or lynx
	* all the bash scripts default prefix to c:/progra~1/Wv
	* all the bash scripts default datadir to /share/wv
	* all the bash scripts cant set the prefix or datadir 

* zimg crashes

**Comment by bastianeicher** [comment]
Hello @pmiess,

thank you for the present. :)

I think http://repo.roscidus.com/ might be a better home for these feeds than http://0install.de/feeds/.

I would the following steps:
- Check if there are existing feeds at repo.roscidus.com for any of these tools, and if so add the gnuwin32 implementations to these.
- Find appropriate categories in repo.roscidus.com for the remaining feeds (probably mostly `utils`).
- Add `<package-implementation>`s to all of the feeds.
- Create [0template](https://github.com/0install/0template) (`*.xml.template`) and [0watch](https://github.com/0install/0watch) (`*.watch.py`) files for auto-updating the feeds in the future.

The result would be a quite comprehensive set of feeds on repo.roscidus.com that allow cross-platform use of GNU tools.

@talex5 What do you think about this?

Regards
Bastian

**Comment by pmiess** [comment]
If I mix them in with other distributions how shall I keep the binary deps separate? These cant use cygwin/msys dlls. Should I create a new distribution (gnuwin32) to depend on?

They already have package-implementation elements

I don't think templates and 0watch files are useful since gnuwin32 hasn't updated since 2010 and shows no signs of returning.

I'd like to hear what @talex5 says how he would like them merged first.
Should I do them all in one group or break it out into individual packages or something in between?

**Comment by pmiess** [comment]
would the FSF object to the 
[https://pmiess.gitlab.io/0install-feeds/glut.xml](https://pmiess.gitlab.io/0install-feeds/glut.xml)
Its license does not allow anyone to distribute modified library code.

**Comment by talex5** [comment]
https://www.opengl.org/resources/libraries/glut/ says "GLUT is not open source".

I'm not very enthusiastic about having these on repo.roscidus.com because it means I have to review all the PRs, even though I don't use Windows or know anything about it.

Perhaps we could host the archives and feeds elsewhere, and just import the cross-platform ones from feeds on repo.roscidus.com? Then you can update them without involving me.

(though we should probably figure out how to let more than one person maintain repo.roscidus.com anyway)

**Comment by pmiess** [comment]
@talex5, the rest of the feeds are open source. 
Its just this particular dependency that is not. The main feeds are all cross platform command line tools ported to Windows. All the feeds use archives hosted on other servers already, mostly sourceforge and github.

 I don't expect them to be updated since they are feeds for a dead project.
If you dont want the rest of gnuwin32 feeds on repo.roscidus.com though I guess we will have to put them elsewhere.   I hope someone reviews the feeds after I submit them so any mistakes I've made can be discovered. 


Once we figure out where we want them I'll create the import feeds for repo.roscidus.com
@bastianeicher would you like them here now?

**Comment by pmiess** [comment]
I have posted pull requests for all the gnuwin32 package in at least 120 repositories on repology.
Flex has been waiting since august and is at this time in 120 repositories on repology. I presume since it has not been merged that it is to obscure for this repository 
_as posted by @talex5 in https://github.com/0install/repo.roscidus.com/pull/154#issuecomment-513460156_
Consequently I believe that all of the remaining feeds I offered are not wanted.  Should something left out be desired I would be glad to submit it if notified.

**Comment by pmiess** [comment]
I have packaged a selection of PNG optimizers
All of them show up on repology but under the 120 repository threshold

- [advancecomp](https://pmiess.gitlab.io/0install-feeds/advancecomp.xml)
- [imageworsener](https://pmiess.gitlab.io/0install-feeds/imageworsener.xml)
- [optipng](https://pmiess.gitlab.io/0install-feeds/optipng.xml)
- [pngcrush](https://pmiess.gitlab.io/0install-feeds/pngcrush.xml)
- [pngnqs9](https://pmiess.gitlab.io/0install-feeds/pngnqs9.xml)
- [pngout](https://pmiess.gitlab.io/0install-feeds/pngout.xml)
- [pngrewrite](https://pmiess.gitlab.io/0install-feeds/pngrewrite.xml)

mingw64 (including dependencies)
- [optipng](https://pmiess.gitlab.io/0install-feeds/mingw64/optipng.xml)
- [pngcrush](https://pmiess.gitlab.io/0install-feeds/mingw64/pngcrush.xml)
- [pngnq](https://pmiess.gitlab.io/0install-feeds/mingw64/pngnq.xml)


also [nircmd](https://pmiess.gitlab.io/0install-feeds/nircmd.xml)

**Comment by pmiess** [comment]
I have packaged cloc and its dependencies.
it shows up on repology below the 120 repository threshold

https://gitlab.com/pmiess/0install-feeds/blob/test/public/cloc.xml

**Comment by pmiess** [comment]
I have packaged [finddupe.exe](https://gitlab.com/pmiess/0install-feeds/raw/test/public/finddupe.xml) and [DupeMerge.exe](https://gitlab.com/pmiess/0install-feeds/raw/test/public/dupemerge.xml)

Neither of these show up on repology.

Dupemerge requires MSVC140. I set it to optional so it runs if you manual install the dependency.

**Comment by pmiess** [comment]
As I noticed that flex was merged, I have prepared branches to make pull requests for all the gnuwin32 package in at least 91 repositories on repology. Once the transition is done I can create pull requests on the new repository for these packages.
Byacc has been waiting since august and is at this time in 91 repositories on repology. I presume since it has not been merged that it is to obscure for this repository
Consequently I believe that all of the remaining feeds I offered are not wanted. Should something left out be desired I would be glad to submit it if notified.

**Comment by pmiess** [comment]
I have packaged [upx](https://gitlab.com/pmiess/0install-feeds/raw/test/public/upx.xml)

it shows up on repology below the 91 repository threshold

**Comment by bastianeicher** [comment]
> As I noticed that flex was merged, I have prepared branches to make pull requests for all the gnuwin32 package in at least 91 repositories on repology. Once the transition is done I can create pull requests on the new repository for these packages.
> Byacc has been waiting since august and is at this time in 91 repositories on repology. I presume since it has not been merged that it is to obscure for this repository
> Consequently I believe that all of the remaining feeds I offered are not wanted. Should something left out be desired I would be glad to submit it if notified.

I focused on merging feeds for apps that I know and have used myself. I have not had the time to review the rest of them yet, but that does not necessarily mean they are not wanted/suitable for the repository.

**Comment by pmiess** [comment]
OK, given that lack of merging is not an good indicator, the only measure of obscurity I have is that awaka is too obscure, so I'll package up the feeds that appear on repology in 5 or more repositories.

**Comment by pmiess** [comment]
I have now made feeds for all the gnuwin32 packages in more than 4 repos on repology
Let me know when you want me to start submitting the pull requests.
Should something left out be desired I would be glad to submit it if notified.
The following are feeds I didn't make packages for grouped by reason

obscurity
-    asciichart
-    bm2font
-    chsuff
-    crypt( a packaging of the gnu libc crypt function as a command line app )
-    cygutil
-    dehtmll
-    deroff
-    dvidjk
-    fax2png
-    fdlibm
-    filetype
-    gsar
-    hextools
-    img2ps2
-    jpg2ps
-    libungif
-    nenscript
-    palm-pbitmtopbm.xml
-    palm-ppmtotbmp.xml
-    pbmadd
-    piechart
-    psmark
-    pngutils its a combo of a bunch of png tools normally packaged separately
-    ntfsprogs
-    scribe2latex
-    sunrpc
-    tiff-win32 a modified version of the tiff package using the win32 file api
-    xpm2wico
-    finddupe.exe 
-    DupeMerge.exe

bugs listed above
- a2ps
- palm-imgvtopgm.xml	
- autoconf
- automake
- glpk
- groff
- libtool
- openssl
- sharutils
- tar
- texinfo

unused libraries

-    libart_lgpl
-    libconfig
-    libopennet only used by libconfig
-    libungif
-    libutf8
-    libxmi
-    termcap
-    pdcurses
-    rx
